import ctypes
from ctypes.wintypes import MSG
from PyQt5 import uic,QtWidgets
from PyQt5.QtWidgets import QMessageBox
import sqlite3

while True:
#Função para pegar os dados do formulario.ui e cadastrar no banco de dados.
    def funcao_principal():
        curso = str(formulario.curso.text().title())
        email = str(formulario.email.text().title())
        horario = str(formulario.horario.currentText())
        datainicio = str(formulario.datainicio.text().title())
        nome = str(formulario.nome.text().title())
        datanasc = str(formulario.datanasc.text())
        idade = str(formulario.idade.text())
        cor = str(formulario.cor.currentText())
        sexo = str(formulario.sexo.currentText())
        estadocivil = str(formulario.estadocivil.currentText())
        filiacao = str(formulario.filiacao.text().title())
        naturalidade = str(formulario.naturalidade.text().title())
        uf = str(formulario.uf.text().upper())
        tmoradia = str(formulario.tmoradia.currentText())
        endereco = str(formulario.endereco.text().title())
        numero = str(formulario.numero.text().title())
        cep = str(formulario.cep.text())
        bairro = str(formulario.bairro.text().title())
        telefone1 = str(formulario.telefone1.text().title())
        telefone2 = str(formulario.telefone2.text().title())
        rg = str(formulario.rg.text().title())
        orgaoexp = str(formulario.orgaoexp.text().upper())
        dataemissao = str(formulario.dataemissao.text())
        cpf = str(formulario.cpf.text())
        deficiencia = str(formulario.deficiencia.text().title())
        escolaridade = str(formulario.escolaridade.currentText())
        situacao = str(formulario.situacao.currentText())
        renda = str(formulario.renda.text().title())
        nummoradores = str(formulario.nummoradores.text().title())
        rendamoradores = str(formulario.rendamoradores.text().title())
        residencia = str(formulario.residencia.currentText())
        valorresidencia = str(formulario.valorresidencia.text())
        numtrabalham = str(formulario.numtrabalham.text())
        observacao = str(formulario.observacao.text())
        datainscricao = str(formulario.datainscricao.text())
        fezcurso = str(formulario.fezcurso.text())

        if curso == "" or nome =="" or telefone1=="":
            ctypes.windll.user32.MessageBoxW(0, "ATENTE-SE AOS CAMPOS OBRIGATÓRIOS PARA A INSCRIÇÃO", "ATENÇÃO!", 0)  
        else:
            banco = sqlite3.connect('banco_cadastro.db')
            cursor = banco.cursor()
            cursor.execute("CREATE TABLE IF NOT EXISTS dados (Curso text,Horario text, DataInicio text, fezcuro text, email text, Data_Inscricao, Nome text, datanasc text, Idade text, Cor text, Sexo text, Estadocivil text, Filiacao text, Naturalidade text, Uf text, Tempomoradia text, Endereco text, Num text, Cep text, Bairro text, Telefone1 text, Telefone2 text, Rg text, OrgaoEmissor text, DataEmissao text, Cpf text, Deficiencia text, Escolaridade text, Situacao text, Renda text, NumMoradores text, numtrabalham text, RendaTotal text, Residencia text, ValorResidencia text, observacao text)")
            cursor.execute("INSERT INTO dados VALUES ('"+curso+"','"+horario+"','"+datainicio+"','"+fezcurso+"', '"+email+"', '"+datainscricao+"', '"+nome+"', '"+datanasc+"', '"+idade+"', '"+cor+"', '"+sexo+"', '"+estadocivil+"', '"+filiacao+"', '"+naturalidade+"', '"+uf+"', '"+tmoradia+"', '"+endereco+"', '"+numero+"','"+cep+"', '"+bairro+"', '"+telefone1+"', '"+telefone2+"', '"+rg+"', '"+orgaoexp+"', '"+dataemissao+"', '"+cpf+"','"+deficiencia+"', '"+escolaridade+"','"+situacao+"','"+renda+"', '"+nummoradores+"','"+numtrabalham+"', '"+rendamoradores+"','"+residencia+"','"+valorresidencia+"','"+observacao+"')")
            banco.commit()
            formulario.curso.setText("")
            formulario.datainicio.setText("")
            formulario.fezcurso.setText("")
            formulario.email.setText("")
            formulario.datainscricao.setText("")
            formulario.nome.setText("")
            formulario.datanasc.setText("")
            formulario.idade.setText("")
            formulario.filiacao.setText("")
            formulario.naturalidade.setText("")
            formulario.uf.setText("")
            formulario.endereco.setText("")
            formulario.numero.setText("")
            formulario.cep.setText("")
            formulario.bairro.setText("")
            formulario.telefone1.setText("")
            formulario.telefone2.setText("")
            formulario.rg.setText("")
            formulario.orgaoexp.setText("")
            formulario.dataemissao.setText("")
            formulario.cpf.setText("")
            formulario.deficiencia.setText("")
            formulario.renda.setText("")
            formulario.nummoradores.setText("")
            formulario.rendamoradores.setText("")
            formulario.valorresidencia.setText("")
            formulario.numtrabalham.setText("")
            formulario.observacao.setText("")
            formulario.horario.setCurrentIndex (0)
            formulario.cor.setCurrentIndex (0)
            formulario.sexo.setCurrentIndex (0)
            formulario.estadocivil.setCurrentIndex (0)
            formulario.tmoradia.setCurrentIndex (0)
            formulario.escolaridade.setCurrentIndex (0)
            formulario.situacao.setCurrentIndex (0)
            formulario.residencia.setCurrentIndex (0)
            ctypes.windll.user32.MessageBoxW(0, "DADOS INSERIDOS COM SUCESSO!", "OBRIGADO!", 0)
            banco.close

#Função para limpar os campos e atribuir ao botão limpar.
    def limpar():
        formulario.curso.setText("")
        formulario.datainicio.setText("")
        formulario.fezcurso.setText("")
        formulario.email.setText("")
        formulario.datainscricao.setText("")
        formulario.nome.setText("")
        formulario.datanasc.setText("")
        formulario.idade.setText("")
        formulario.filiacao.setText("")
        formulario.naturalidade.setText("")
        formulario.uf.setText("")
        formulario.endereco.setText("")
        formulario.numero.setText("")
        formulario.cep.setText("")
        formulario.bairro.setText("")
        formulario.telefone1.setText("")
        formulario.telefone2.setText("")
        formulario.rg.setText("")
        formulario.orgaoexp.setText("")
        formulario.dataemissao.setText("")
        formulario.cpf.setText("")
        formulario.deficiencia.setText("")
        formulario.renda.setText("")
        formulario.nummoradores.setText("")
        formulario.rendamoradores.setText("")
        formulario.valorresidencia.setText("")
        formulario.numtrabalham.setText("")
        formulario.observacao.setText("")
        formulario.horario.setCurrentIndex (0)
        formulario.cor.setCurrentIndex (0)
        formulario.sexo.setCurrentIndex (0)
        formulario.estadocivil.setCurrentIndex (0)
        formulario.tmoradia.setCurrentIndex (0)
        formulario.escolaridade.setCurrentIndex (0)
        formulario.situacao.setCurrentIndex (0)
        formulario.residencia.setCurrentIndex (0)
        ctypes.windll.user32.MessageBoxW(0, "DADOS LIMPOS!!", "SUCESSO!", 0)

#Abrindo a aplicação.
    app=QtWidgets.QApplication([])
    formulario=uic.loadUi("formulario.ui")
    formulario.botao_2.clicked.connect(funcao_principal)
    formulario.botao_1.clicked.connect(limpar)
    formulario.horario.addItems([" ","08:00","09:00","13:00","14:00","14:30","14:40", "15:00","16:00","16:20","18:00", "19:00", "20:00"])
    formulario.cor.addItems([" ","Branca","Preta","Negra","Parda","Amarela","Indigena"])
    formulario.sexo.addItems([" ","Masculino","Feminino","Outros"])
    formulario.estadocivil.addItems([" ","Solteiro(a)","Casado(a)","Separado(a)","União Estável","Viúvo(a)"])
    formulario.tmoradia.addItems([" ","Natural","Menos de 5 anos","Mais de 5 anos"])
    formulario.escolaridade.addItems([" ","Fundamental Completo","Fundamental Incompleto","Ensino Médio Completo","Ensino Médio Incompleto","Superior Completo","Superior Incompleto"])
    formulario.situacao.addItems([" ","Empregado","Desempregado","Inss","Autônomo","Auxílio","Aposentado","Estudante"])
    formulario.residencia.addItems([" ","Própria","Alugada","Financiada","Cedida"])

    formulario.show()
    app.exec()
